### ISSUE TITLE
ECHint looking into binary files

### ISSUE THREAD

**Issue by Clement-TS** [ahmadnassri/echint#67]
Hi,
thank your first for the package, I may add it to numerous projects here :)

I'm experiencing a lot of warnings in the echint output due to binary files, such as *.gif*, *.png*, *.woff*, *.xcf*, or even text files I would like to avoid checking (*.svg* for instance).

Is there a better way than configuring my _package.json_ like this:
```json
"echint": {
    "ignore": [
      "**/node_modules/**",
      "**/bower_components/**",
      "**/*.xcf",
      "**/*.jpg",
      "**/*.svg",
      "**/*.png",
      "**/*.gif"
    ]
  }
```

Plus this seems to be applied after the full check (filtering output, instead of input), which takes a lot of time processing my (big) project.

Thank you

**Comment by stefanmaric** [comment]
> Is there a better way than configuring my package.json like this:

These globs will also work (which are no more than nicer to look at):

```json
{
  "echint": {
    "ignore": [
      "node_modules/**",
      "bower_components/**",
      "**/*.{gif,jpg,png,svg,xcf}"
    ]
  }
}
```

But indeed, `echint` filters out ignored paths after hinting the whole working tree so it takes forever. Maybe this issue can be renamed as "echint looking into ignored files".

**Comment by ahmadnassri** [comment]
@stefanmaric thanks for the clarification ... not sure how this behaviour (looking into ignored files) is occuring yet. but I will investigate and add a default binary filter.

**Comment by stefanmaric** [comment]
@ahmadnassri so I'm doing some testing. Some findings:

If I add `node_modules/**` or `**/node_modules/**` (which is ignored by default) to `echint.ignore` in `package.json`, it goes from 2s to 15s to complete on my testing project (this is what initially triggered my research on `echint`'s issues). So there's something wrong with trying to override default ignore globs itself and not actually with hinting ignored globs.

Also this glob pattern might be wrong (need curly braces (`{}`) instead of square brackets (`[]`)) since echint still hints those filetypes on my testing project: https://github.com/ahmadnassri/echint/blob/master/src/index.js#L18

**Comment by stefanmaric** [comment]
@ahmadnassri so I think that might be actually occurring is that the `opts.ignore` list is getting insanely huge if you add `node_modules` to `ignore`:

https://github.com/ahmadnassri/echint/blob/master/src/index.js#L85

As I can see in debug info:

```shell
ECHINT 1099: scanning for files matching ignore pattern "node_modules/**"
ECHINT 1099: found "19898" files to ignore
```

That array is queried for each matched file in here: https://github.com/ahmadnassri/echint/blob/master/src/index.js#L117

Which I don't think is necessary since they are being passed to `glob` here: https://github.com/ahmadnassri/echint/blob/master/src/index.js#L110

So I think we could delete the conditional in [line 117](https://github.com/ahmadnassri/echint/blob/master/src/index.js#L117) and performance should improve considerably.

**Comment by stefanmaric** [comment]
Another finding is that the list of files is not actually working. If I run:

```shell
$ echint *.js
```

I get this debug message:

```
ECHINT 2394: no file list given, using match pattern instead: "**/*"
```

I could open separated issues and/or open a PR if I get the change to tackle these.

**Comment by ahmadnassri** [comment]
@stefanmaric appreciate the detailed and thorough analysis!!! I'm currently away from any viable coding machines (just got a tablet!) and will not be close to one for at least 4 hours.

happy to take a PR if you've got the time, else I will surely jump on this later.

**Comment by stefanmaric** [comment]
@ahmadnassri I submitted 2 PR, one to fix the default image ignore pattern and another to fix `echint` command actually ignoring any file you pass (e.g. `echint *.js` doesn't actually care about the `*.js` part).

The performance issue with the ignore list can be easily fixed:

Instead of generating a list of files using `glob`, we simply import `minmatch` and check the file path against each of the ignore patterns.

I will summit a PR for that later today if I get the chance.

**Comment by stefanmaric** [comment]
@ahmadnassri any news on #69 and #70? I saw you refactored some stuff on master and those PRs are conflicting now. Let me know and I can merge downstream, fix the conflicts and update the PRs for easy merging.

**Comment by ahmadnassri** [comment]
@stefanmaric I ended up with some more refactoring locally, gonna try to clear up my queue and get those out soon (needs more thorough testing) no need to update your PRs I already merged them locally :+1:

**Comment by stefanmaric** [comment]
Awesome @ahmadnassri !

**Comment by stefanmaric** [comment]
#68, #69 and #70 have been merged. This can be closed.

**Comment by Clement-TS** [comment]
Thank you guys!
